<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>FCCCodeDesktop.Files</RootNamespace>
    <AssemblyName>FCCCodeDesktop.Files</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FCCCodeDesktop.Core\FCCCodeDesktop.Core.csproj" />
    <ProjectReference Include="..\FCCCodeDesktop.Application\FCCCodeDesktop.Application.csproj" />
  </ItemGroup>
</Project>
