#!/usr/bin/env node
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import {
  buildBuildArgs, buildCreateProjectArgs, buildExecuteMethodArgs, buildTestArgs, classifyCompile,
  compareUnityVersions, detectUnityProject, describeArtifact, EVIDENCE, makeDisposableFixtureRoot,
  operationRecord, parseProjectVersionText, parseUnityLogText, redact, resolveEditorForProject,
  runOwnedProcess, sanitizeForPersistence, validateBuildArtifacts, validateJsonResult,
  validateTestResultXml, writeDisposableFixtureSources,
} from './lib.mjs';

let passed = 0, failed = 0; const details = [];
function test(name, fn) { return Promise.resolve().then(fn).then(() => { passed++; details.push({ name, status: 'PASS' }); console.log(`PASS ${name}`); }).catch((error) => { failed++; details.push({ name, status: 'FAIL', error: String(error?.stack ?? error) }); console.error(`FAIL ${name}: ${error?.stack ?? error}`); }); }
function assert(condition, message) { if (!condition) throw new Error(message); }
function equal(actual, expected, message) { if (actual !== expected) throw new Error(`${message}: expected=${expected} actual=${actual}`); }

const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'fccd-unity-selftest-'));
try {
  await test('ProjectVersion parser extracts editor version and revision', () => { const p = parseProjectVersionText('m_EditorVersion: 6000.0.65f1\nm_EditorVersionWithRevision: 6000.0.65f1 (abcdef123456)\n'); equal(p.requiredVersion, '6000.0.65f1', 'required version'); equal(p.revision, 'abcdef123456', 'revision'); });
  await test('Valid Unity project detected without launching Unity', () => { const root = path.join(temp, 'Project With Spaces عربي'); fs.mkdirSync(path.join(root, 'Assets'), { recursive: true }); fs.mkdirSync(path.join(root, 'Packages'), { recursive: true }); fs.mkdirSync(path.join(root, 'ProjectSettings'), { recursive: true }); fs.writeFileSync(path.join(root, 'ProjectSettings', 'ProjectVersion.txt'), 'm_EditorVersion: 2022.3.62f1\nm_EditorVersionWithRevision: 2022.3.62f1 (deadbeef)\n'); const d = detectUnityProject(root); assert(d.valid, 'project should be valid'); equal(d.requiredVersion, '2022.3.62f1', 'version'); equal(d.revision, 'deadbeef', 'revision'); });
  await test('Invalid directory classified cleanly', () => { const root = path.join(temp, 'not-unity'); fs.mkdirSync(root); const d = detectUnityProject(root); assert(!d.valid, 'must be invalid'); equal(d.classification, 'NOT_UNITY_PROJECT', 'classification'); });
  await test('Version comparison orders alpha beta final patch and numeric builds', () => { assert(compareUnityVersions('6000.0.1f1', '6000.0.1b9') > 0, 'final after beta'); assert(compareUnityVersions('2022.3.62f1', '2022.3.9f1') > 0, 'numeric patch comparison'); assert(compareUnityVersions('2022.3.62p1', '2022.3.62f1') > 0, 'patch release after final'); });
  await test('Exact project version resolution never silently upgrades', () => { const editors = [{ version: '6000.0.65f1', path: 'C:/Unity/6000/Unity.exe' }, { version: '2022.3.62f1', path: 'C:/Unity/2022/Unity.exe' }]; const r = resolveEditorForProject({ valid: true, requiredVersion: '2022.3.62f1' }, editors); equal(r.compatibilityStatus, 'EXACT_MATCH', 'compatibility'); equal(r.selectedEditor.version, '2022.3.62f1', 'selection'); const missing = resolveEditorForProject({ valid: true, requiredVersion: '2021.3.1f1' }, editors); equal(missing.compatibilityStatus, 'REQUIRED_VERSION_NOT_INSTALLED', 'must not select another editor'); equal(missing.selectedEditor, null, 'no silent fallback'); });
  await test('Command builders preserve spaces Unicode and Arabic as single arguments', () => { const projectPath = 'C:\\Unity Projects\\مشروع تجريبي Ω', logPath = 'C:\\Probe Logs\\Unity Log عربي.txt', resultPath = 'C:\\Probe Results\\Edit Mode Ω.xml'; for (const args of [buildCreateProjectArgs({ projectPath, logPath }), buildExecuteMethodArgs({ projectPath, logPath, method: 'FccUnityProbe.AutomationMarker', extraArgs: ['--fcc-result', 'C:\\Result Folder\\نتيجة.json'] }), buildTestArgs({ projectPath, logPath, resultsPath: resultPath, platform: 'EditMode' }), buildBuildArgs({ projectPath, logPath, buildOutputPath: 'C:\\Build Folder\\لعبة.exe', buildResultPath: 'C:\\Build Folder\\build-result.json' })]) { assert(args.includes(projectPath), 'project path must be one arg'); assert(args.includes(logPath), 'log path must be one arg'); assert(!args.some((a) => a.includes('"')), 'builder must not add shell quotes'); } });
  await test('Test XML validator accepts NUnit result with plausible count', () => { const p = path.join(temp, 'pass.xml'); fs.writeFileSync(p, '<?xml version="1.0"?><test-run total="2" passed="2" failed="0" skipped="0" inconclusive="0" result="Passed"></test-run>'); const v = validateTestResultXml(p); assert(v.valid, JSON.stringify(v)); equal(v.counts.total, 2, 'total'); });
  await test('Test XML validator rejects failed tests', () => { const p = path.join(temp, 'failed.xml'); fs.writeFileSync(p, '<test-run total="2" passed="1" failed="1" skipped="0" inconclusive="0" result="Failed"></test-run>'); const v = validateTestResultXml(p); assert(!v.valid, 'must fail'); equal(v.classification, 'TEST_FAILURE', 'classification'); });
  await test('Test XML validator rejects zero tests and missing artifact', () => { const p = path.join(temp, 'zero.xml'); fs.writeFileSync(p, '<test-run total="0" passed="0" failed="0" skipped="0" inconclusive="0" result="Passed"></test-run>'); equal(validateTestResultXml(p).classification, 'ZERO_TESTS', 'zero tests'); equal(validateTestResultXml(path.join(temp, 'missing.xml')).classification, 'TEST_RESULTS_MISSING', 'missing'); });
  await test('JSON result validation requires structured artifact content', () => { const p = path.join(temp, 'result.json'); fs.writeFileSync(p, '{"success":true,"operation":"automation-marker"}'); assert(validateJsonResult(p, (v) => v.success === true && v.operation === 'automation-marker').valid, 'valid json result'); assert(!validateJsonResult(p, (v) => v.success === false).valid, 'predicate must fail'); });
  await test('Build validation rejects exit-code-only success when artifact missing', () => { const result = path.join(temp, 'build-result.json'); fs.writeFileSync(result, '{"success":true,"result":"Succeeded"}'); assert(!validateBuildArtifacts({ buildResultPath: result, expectedExecutablePath: path.join(temp, 'missing.exe') }).valid, 'missing build output must fail'); });
  await test('Log parser surfaces compile errors project locks and preserves unknown lines', () => { const p = parseUnityLogText('Assets/Foo.cs(1,2): error CS1002: ; expected\nProject is already open in another Unity Editor.\nFCCD_UNKNOWN_EVENT keep me'); equal(p.categories.compilerError, 1, 'compiler errors'); equal(p.categories.projectLock, 1, 'project lock'); assert(p.events.some((e) => e.kind === 'UNKNOWN' && e.line.includes('FCCD_UNKNOWN_EVENT')), 'unknown must be preserved'); });
  await test('Compile classification distinguishes pass error timeout startup and project open failure', () => { equal(classifyCompile({ processResult: { exitCode: 0 }, logResult: { parsed: { categories: {} } }, resultArtifact: { valid: true } }), 'COMPILE_PASS', 'pass'); equal(classifyCompile({ processResult: { exitCode: 1 }, logResult: { parsed: { categories: { compilerError: 1 } } }, resultArtifact: { valid: false } }), 'COMPILE_ERROR', 'compile error'); equal(classifyCompile({ processResult: { timedOut: true }, logResult: { parsed: { categories: {} } }, resultArtifact: null }), 'TIMEOUT', 'timeout'); equal(classifyCompile({ processResult: { launchError: 'missing' }, logResult: { parsed: { categories: {} } }, resultArtifact: null }), 'UNITY_STARTUP_FAILURE', 'startup'); equal(classifyCompile({ processResult: { exitCode: 1 }, logResult: { parsed: { categories: { projectLock: 1 } } }, resultArtifact: null }), 'PROJECT_OPEN_FAILURE', 'project open'); });
  await test('Redaction removes fake keys bearer values and credential-shaped fields', () => { const r = JSON.stringify(redact({ api_key: 'secret-value', line: 'Authorization: Bearer abcdefghijklmnop', github: 'ghp_1234567890abcdef', open: 'sk-abcdefghijklmnop' })); assert(!r.includes('secret-value'), 'api key leaked'); assert(!r.includes('abcdefghijklmnop'), 'credential leaked'); assert(!r.includes('1234567890abcdef'), 'github token leaked'); });
  await test('Owned process timeout terminates only owned child', async () => { const r = await runOwnedProcess(process.execPath, ['-e', 'setInterval(()=>{},1000)'], { timeoutMs: 350, forceAfterMs: 150 }); assert(r.timedOut, 'timeout flag'); assert(r.pid, 'pid'); assert(r.durationMs < 5000, `bounded duration ${r.durationMs}`); });
  await test('Owned process explicit cancellation is classified separately from timeout', async () => { const r = await runOwnedProcess(process.execPath, ['-e', 'setInterval(()=>{},1000)'], { timeoutMs: 5000, cancelAfterMs: 300, forceAfterMs: 150 }); assert(r.cancelled, 'cancel flag'); assert(!r.timedOut, 'must not be timeout'); });
  await test('Disposable fixture source bootstrap writes only underneath owned root', () => { const root = makeDisposableFixtureRoot(temp); fs.mkdirSync(path.join(root, 'Assets'), { recursive: true }); const artifacts = writeDisposableFixtureSources(root); assert(artifacts.length >= 5 && artifacts.every((a) => a.exists && a.size > 0), 'fixture files'); assert(artifacts.every((a) => !String(a.path).includes('..')), 'paths contained'); });
  await test('Artifact manifest captures required operation lifecycle fields', () => { const p = path.join(temp, 'artifact.bin'); fs.writeFileSync(p, 'abc'); const op = operationRecord({ id: 'op-1', unityVersion: '6000.0.65f1', executablePath: 'C:/Unity/Unity.exe', projectPath: 'C:/Project', args: ['-batchmode'], processResult: { startTime: '2026-09-01T00:00:00Z', endTime: '2026-09-01T00:00:01Z', durationMs: 1000, pid: 10, exitCode: 0, timedOut: false, cancelled: false, processCleanup: null }, logPath: 'C:/log.txt', artifacts: [describeArtifact(p)], classification: 'COMPILE_PASS', evidenceState: EVIDENCE.SELF_TEST_VERIFIED }); for (const key of ['operationId','unityVersion','executablePath','projectPath','args','startTime','endTime','durationMs','pid','exitCode','timeout','cancellation','logPath','producedArtifacts','finalClassification']) assert(Object.hasOwn(op, key), `missing ${key}`); });
  await test('Unified target runner invokes Unity probe and preserves Blender ownership boundary', () => { const here = path.dirname(fileURLToPath(import.meta.url)); const runner = path.resolve(here, '..', 'run-target-validation.ps1'); assert(fs.existsSync(runner), 'canonical runner missing'); const text = fs.readFileSync(runner, 'utf8'); assert(text.includes("unity\\probe.mjs") && text.includes('unity-contract-target'), 'Unity target invocation missing'); assert(text.includes('$unityIntegrated = $true'), 'Unity integration flag not true'); assert(text.includes('$blenderIntegrated = $false') && text.includes('FCCD-P00-009'), 'Blender boundary was not preserved'); });
  await test('Persisted manifest secret scan stays clean', () => { const p = path.join(temp, 'manifest.json'); const value = sanitizeForPersistence({ line: 'token=supersecretvalue Authorization: Bearer abcdefghijklmnop', apiKey: 'anothersecretvalue' }); fs.writeFileSync(p, JSON.stringify(value, null, 2)); const txt = fs.readFileSync(p, 'utf8'); assert(!txt.includes('supersecretvalue') && !txt.includes('abcdefghijklmnop') && !txt.includes('anothersecretvalue'), 'secret found'); });
} finally {
  const summary = { schemaVersion: 1, probe: 'FCCD_P00_008_UNITY_SELF_TEST', status: failed === 0 ? EVIDENCE.SELF_TEST_VERIFIED : 'SELF_TEST_FAILED', passed, failed, details };
  const outputPath = process.argv.includes('--json') ? process.argv[process.argv.indexOf('--json') + 1] : null;
  if (outputPath) { fs.mkdirSync(path.dirname(path.resolve(outputPath)), { recursive: true }); fs.writeFileSync(path.resolve(outputPath), JSON.stringify(summary, null, 2) + '\n'); }
  try { fs.rmSync(temp, { recursive: true, force: true }); } catch {}
  console.log(`${summary.status} ${passed}/${passed + failed}`); process.exitCode = failed === 0 ? 0 : 1;
}
